backend:
  name: github
  repo: PharenIT/CMS
  branch: main
  base_url: https://chipper-crumble-c1894a.netlify.app/
  auth_endpoint: api/auth



media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "categories", label: "Categories", widget: "list" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "authors", label: "Authors", widget: "list", fields: [
          { name: "name", label: "Name", widget: "string" },
          { name: "role", label: "Role", widget: "string" },
          { name: "image", label: "Image", widget: "image" }
        ]}
      - { name: "published", label: "Published", widget: "boolean", default: true }
      - { name: "body", label: "Body", widget: "markdown" }
